name: "secure_string"
version: "1.1.0"
description: "Secure random string generation"
author: "Ice Flake <iceflake@cloudwards.es>"
homepage: "https://github.com/iFlake/secure-string"

environment:
    sdk: ">1.24.0 <2.0.0"

dependencies:
